apiVersion: egress.mapper.com/v1alpha1
kind: EgressMapper
metadata:
  name: example-egressmapper
spec:
  KeepalivedVIPImage: k8s.gcr.io/kube-keepalived-vip:0.11
  KubeEgressImage: ssheehy/kube-egress:0.3.1
