kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: egress-mapper
subjects:
- kind: ServiceAccount
  name: egress-mapper
roleRef:
  kind: Role
  name: egress-mapper
  apiGroup: rbac.authorization.k8s.io
